# Kustomization for ArgoCD Applications
# This manages all ArgoCD Application definitions in GitOps fashion
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace where ArgoCD applications should be deployed
namespace: argocd

# List of ArgoCD Application resources to include
resources:
  # Nginx application deployment via GitOps
  - nginx-application.yaml
  # My Service application deployment via GitOps
  - my-service-application.yaml