# Kustomization for ArgoCD installation via Helm chart
# This file bootstraps ArgoCD itself into the cluster
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# All resources will be created in the argocd namespace
namespace: argocd

# Standard Kubernetes resources to include
resources:
  # Creates the argocd namespace before installing the chart
  - namespace.yaml

# Helm chart installations managed by Kustomize
# Note: Requires kubectl with Helm chart inflation support
helmCharts:
  # ArgoCD Helm chart configuration
  - name: argo-cd
    # Include Custom Resource Definitions (required for ArgoCD to function)
    includeCRDs: true
    # Target namespace for the Helm release
    namespace: argocd
    # Helm release name (how it appears in 'helm list')
    releaseName: argocd
    # Official ArgoCD Helm chart repository
    repo: https://argoproj.github.io/argo-helm
    # Custom values file for chart configuration
    valuesFile: "values.yaml"
    # Specific chart version to install (pinned for reproducibility)
    version: 7.7.17 # chart version

